# Generated by Django 5.2.3 on 2025-06-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_profile_bio_profile_city_profile_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
